{
  "hash": "65bbea0a89933c2d6f43b9291c2f958c",
  "result": {
    "markdown": "---\ntitle: \"An Illustrated Guide to TMLE, Part II: The Algorithm\"\nauthor: \"Katherine Hoffman\"\ndate: 2020-12-11\nimage: tmle/tmle_crop.jpeg\npage-layout: article\ncategories: [\"statistics\"]\ndescription: \" \"\noutput:\n  blogdown::html_page:\n    toc: false\n    toc_depth: 1\n---\n\n\n\n\n<html><link rel=\"stylesheet\" href=\"/style.css\" /></html>\n\nThe second post of a three-part series to help beginners and/or visual learners understand Targeted Maximum Likelihood Estimation (TMLE). This section walks through the **TMLE algorithm for the mean difference in outcomes for a binary treatment and binary outcome**. <br> <br> This post is an expansion of a printable \"visual guide\" available on my [Github](https://github.com/kathoffman/causal-inference-visual-guides). I hope it helps analysts who feel out-of-practice reading mathematical notation follow along with the TMLE algorithm. A web-based key without explanations is also available [here](https://khstats.com/blog/tmle/visual-key).\n\n<html>\n\n<head>\n\n<title>HTML Image as link</title>\n\n</head>\n\n<body><a href=\"https://github.com/kathoffman/CI-visual-guides/blob/master/visual-guides/TMLE.pdf\"> <img src=\"/img/tmle/tmle.jpg\" alt=\"cheatsheet\" width=\"100%&quot;\"/> </a></body>\n\n</html>\n\n------------------------------------------------------------------------\n\n⬅️[*Return to Part I: Motivation*](https://khstats.com/blog/tmle/tutorial/)\n\n# Part II: The Algorithm: {#part-ii-the-algorithm}\n\n[Why the Visual Guide? 🎨](#why-the-visual-guide)\n\n[TMLE, Step-by-Step 🚶🏽️](#tmle-step-by-step)\n\n1.  [Estimate the Outcome](#step-1-estimate-the-outcome)\n\n2.  [Estimate the Probability of Treatment](#step-2-estimate-the-probability-of-treatment)\n\n3.  [Estimate the Fluctuation Parameter](#step-3-estimate-the-fluctuation-parameter)\n\n4.  [Update the Initial Estimates of the Expected Outcome](#step-4-update-the-initial-estimates-of-the-expected-outcome)\n\n5.  [Compute the Statistical Estimand of Interest](#step-5-compute-the-statistical-estimand-of-interest)\n\n6.  [Calculate the Standard Errors for Confidence Intervals and P-values](#step-6-calculate-the-standard-errors-for-confidence-intervals-and-p-values)\n\n[Using the `tmle` package 📦](#using-the-tmle-package)\n\n[Full tutorial code 💻](#full-tutorial-code)\n\n➡️[*Skip to Part III: Evaluation*](https://khstats.com/blog/tmle/tutorial-pt3/)\n\n------------------------------------------------------------------------\n\n# Why the Visual Guide? 🎨 {#why-the-visual-guide}\n\nTMLE was developed in 2007 by Mark van der Laan and colleagues at UC Berkeley, and it is slowly but surely starting to see more widespread use. Since learning about TMLE, I've believed many more analysts with a skill set similar to mine *could* be using TMLE, but perhaps find even the most introductory resources to be a bit daunting.\n\nI am a very applied thinker, and I've tried to write this tutorial in the way I would have found most useful and accessible when I began learning about TMLE. Each step is accompanied by:\n\n1.  a non-rigorous explanation\n2.  an equation using the simplest notation possible\n3.  in-line `R` code\n4.  a small graphic representing the computation on a data frame or vector\n\nThis last piece is super important for me, because I remember best when I associate an image with what I've learned. If the graphics are also useful to you, it may be helpful to open this [corresponding key](https://khstats.com/blog/tmle/visual-key) in another browser or print the [visual guide](https://github.com/kathoffman/causal-inference-visual-guides) for reference.\n\nThis tutorial is not meant to replace the resources I used to learn TMLE, but rather to supplement them. I use the same mathematical notation as the TMLE literature to make it easier to move back and forth. I hope you find the way I think about the algorithm useful, but if not, consider checking out the references I've listed in [*Part III*](https://khstats.com/blog/tmle/tutorial-pt3/#resources-to-learn-more). TMLE is a very powerful method and will undoubtedly only grow in popularity in statistics and data science.\n\n# TMLE, Step-by-Step 🚶🏽 {#tmle-step-by-step}\n\nLet's look at the algorithm step-by-step. As you're reading, keep in mind that there are `R` packages that will do this for you as easily as running a `glm()` or `coxph()` function. This tutorial is to help understand what's going on behind-the-scenes.\n\nOne final note before we dive into the algorithm:\n\n### Superlearning\n\nI use the ensemble learning method superlearning (also known as \"stacking\") to demonstrate TMLE. This is because superlearning is theoretically and empirically proven to yield the best results in TMLE.\n\nIf you're new to superlearning/stacking, the necessary knowledge for this post is that it allows you to combine many machine learning algorithms for prediction. When I use `SuperLearner()` in the following example code, I could have used `glm()`, `randomForest()`, or any other parametric or non-parametric supervised learning algorithm.\n\n<html>\n\n<head>\n\n<title>HTML Image as link</title>\n\n</head>\n\n<body><a href=\"https://khstats.com/blog/sl/superlearning\"> <img src=\"/img/Superlearning.jpg\" alt=\"cheatsheet\" width=\"50%\" style=\"float:right; padding-left:60px;\"/> </a></body>\n\n</html>\n\nNote that the choice of base learners for superlearning is not the point of this post. In practice we simply want to add flexible machine learning models which we think **may** reflect the underlying data distribution. For a tutorial on superlearning, you can check out one of my [previous blog posts](https://khstats.com/blog/sl/superlearning).\n\n### Initial set up\n\nLet's first load the necessary libraries and set a seed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) # for data manipulation\nlibrary(gt) # for table printing\nlibrary(SuperLearner) # for ensemble learning\n\nset.seed(7) # for reproducible results\n```\n:::\n\n\nNext, let's simulate a data set for demonstration of the algorithm. This data will have a very simple structure: a binary treatment, $A$; binary outcome, $Y$; and four confounders: $W_1$, $W_2$, $W_3$, and $W_4$.\n\n![](/img/tmle/1_data_structure.png){width=\"80%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_data <- function(n){ \n    W1 <- rbinom(n, size=1, prob=0.2) # binary confounder\n    W2 <- rbinom(n, size=1, prob=0.5) # binary confounder\n    W3 <- round(runif(n, min=2, max=7)) # continuous confounder\n    W4 <- round(runif(n, min=0, max=4)) # continuous confounder\n    A  <- rbinom(n, size=1, prob= plogis(-0.2 + 0.2*W2 + log(0.1*W3) + 0.3*W4 + 0.2*W1*W4)) # binary treatment depends on confounders\n    Y <- rbinom(n, size=1, prob= plogis(-1 + A - 0.1*W1 + 0.2*W2 + 0.3*W3 - 0.1*W4 + sin(0.1*W2*W4))) # binary outcome depends on confounders\n    return(tibble(Y, W1, W2, W3, W4, A))\n}\n\nn <- 1000\ndat_obs <- generate_data(n) # generate a data set with n observations\n\ndat_obs %>%\n  head() %>%\n  gt() %>%\n  tab_header(\"Simulated data set.\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"fkgwpykulw\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#fkgwpykulw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fkgwpykulw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fkgwpykulw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fkgwpykulw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fkgwpykulw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fkgwpykulw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fkgwpykulw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fkgwpykulw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fkgwpykulw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fkgwpykulw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fkgwpykulw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fkgwpykulw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fkgwpykulw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkgwpykulw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fkgwpykulw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fkgwpykulw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkgwpykulw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fkgwpykulw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkgwpykulw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fkgwpykulw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkgwpykulw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fkgwpykulw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fkgwpykulw .gt_left {\n  text-align: left;\n}\n\n#fkgwpykulw .gt_center {\n  text-align: center;\n}\n\n#fkgwpykulw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fkgwpykulw .gt_font_normal {\n  font-weight: normal;\n}\n\n#fkgwpykulw .gt_font_bold {\n  font-weight: bold;\n}\n\n#fkgwpykulw .gt_font_italic {\n  font-style: italic;\n}\n\n#fkgwpykulw .gt_super {\n  font-size: 65%;\n}\n\n#fkgwpykulw .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#fkgwpykulw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fkgwpykulw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fkgwpykulw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fkgwpykulw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fkgwpykulw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fkgwpykulw .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  <thead class=\"gt_header\">\n    <tr>\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Simulated data set.</td>\n    </tr>\n    \n  </thead>\n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Y</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">W1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">W2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">W3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">W4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">A</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">6</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td></tr>\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">6</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">0</td></tr>\n    <tr><td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">0</td></tr>\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td></tr>\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">0</td></tr>\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">6</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nAs mentioned earlier, TMLE can estimate many different statistical estimands of interest. In this example, our statistical estimand is the mean difference in outcomes between those who received the treatment and those who did not, adjusting for confounders.\n\nUnder causal assumptions, this could be *identifiable* as the Average Treatment Effect (ATE). I won't go through the identification process here (see [*Part III, References*](https://khstats.com/blog/tmle/tutorial-pt3/#resources-to-learn-more)), but since TMLE is often used for causal inference, let's pretend for this example that we previously met causal assumptions and call our statistical estimand, $\\Psi$, the ATE.\n\n$$ATE = \\Psi = E_W[\\mathrm{E}[Y|A=1,\\mathbf{W}] - \\mathrm{E}[Y|A=0,\\mathbf{W}]]$$\n\nThe ATE, once we estimate it, will be interpretable as the mean difference in outcomes in a hypothetical world where everyone received the treatment compared to a hypothetical world where no one received the treatment.\n\nAt this point in set-up, we should also pick our base machine learning algorithms to combine via superlearning to estimate the expected outcome and probability of treatment. Let's use LASSO (`glmnet`), random forests (`ranger`), Multivariate Adaptive Regression Splines (MARS) (`earth`), and a generalized linear model (`glm`) for demonstration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsl_libs <- c('SL.glmnet', 'SL.ranger', 'SL.earth', 'SL.glm') # a library of machine learning algorithms (penalized regression, random forests, and multivariate adaptive regression splines)\n```\n:::\n\n\n## Step 1: Estimate the Outcome {#step-1-estimate-the-outcome}\n\nThe very first step of TMLE is to **estimate the expected value of the outcome** using treatment and confounders as predictors.\n\nThis is what that looks like in mathematical notation. There is some function $Q$ which takes $A$ and $\\mathbf{W}$ as inputs and yields the conditional expectation of $Y$:\n\n$$Q(A,\\mathbf{W}) = \\mathrm{E}[Y|A,\\mathbf{W}]$$ We can use any regression to estimate this conditional expectation, but it is best to use flexible machine learning models so that we don't have unnecessary assumptions on the underlying distribution of the data.\n\nWe can think about the above equation as some generic regression function in `R` called `fit()` with inputs in formula form: `outcome ~ predictors`:\n\n![](/img/tmle/2_outcome_fit.png){width=\"70%\"} In real `R` code, we'll use the `SuperLearner()` function to fit a weighted combination of multiple machine learning models (defined earlier in `sl_libs`). This function takes the outcome `Y` as a vector and a data frame `X` as predictors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nY <- dat_obs$Y\nW_A <- dat_obs %>% select(-Y) # remove the outcome to make a matrix of predictors (A, W1, W2, W3, W4) for SuperLearner\nQ <- SuperLearner(Y = Y, # Y is the outcome vector\n                  X = W_A, # W_A is the matrix of W1, W2, W3, W4, and A\n                  family=binomial(), # specify we have a binary outcome\n                  SL.library = sl_libs) # specify our superlearner library of LASSO, RF, and MARS\n```\n:::\n\n\nThen, we should estimate the outcome for every observation under three different scenarios:\n\n**1. If every observation received the treatment they *actually* received.**\n\nWe can get this expected outcome estimate by simply calling `predict()` on the model fit without specifying any new data.\n\n$$\\hat{Q}(A,\\mathbf{W}) = \\mathrm{\\hat{E}}[Y|A,\\mathbf{W}]$$\n\nWe will save that vector of estimates as a new object in `R`.\n\n![](/img/tmle/3_QA.png){width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ_A <- as.vector(predict(Q)$pred) # obtain predictions for everyone using the treatment they actually received\n```\n:::\n\n\n**2. If every observation received the treatment.**\n\nTo do this, we'll first need to create a data set where every observation received the treatment of interest, whether they actually did or not. Then we can call the `predict()` function on that data set.\n\n$$\\hat{Q}(1,\\mathbf{W}) = \\mathrm{\\hat{E}}[Y|A=1,\\mathbf{W}]$$\n\n![](/img/tmle/4_Q1.png){width=\"80%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW_A1 <- W_A %>% mutate(A = 1)  # data set where everyone received treatment\nQ_1 <- as.vector(predict(Q, newdata = W_A1)$pred) # predict on that everyone-exposed data set\n```\n:::\n\n\n**3. If every observation received the control.**\n\nSimilarly, we create a data set where every observation did *not* receive the treatment of interest, whether they actually did or not, and call the `predict()` function again.\n\n$$\\hat{Q}(0,\\mathbf{W}) = \\mathrm{\\hat{E}}[Y|A=0,\\mathbf{W}]$$\n\n![](/img/tmle/5_Q1.png){width=\"80%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW_A0 <- W_A %>% mutate(A = 0) # data set where no one received treatment\nQ_0 <- as.vector(predict(Q, newdata = W_A0)$pred)\n```\n:::\n\n\n***Next***, let's create a new data frame, `dat_tmle`, to hold the three vectors we've created so far, along with the treatment status $A$ and observed outcome $Y$. Notice that when $A=1$, the expected outcome $\\mathrm{\\hat{E}}[Y|A,\\mathbf{W}]$ equals the expected outcome under treatment $\\mathrm{\\hat{E}}[Y|A=1,\\mathbf{W}]$. When $A=0$, the expected outcome $\\mathrm{\\hat{E}}[Y|A,\\mathbf{W}]$ equals the expected outcome under no treatment $\\mathrm{\\hat{E}}[Y|A=0,\\mathbf{W}]$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_tmle <- tibble(Y = dat_obs$Y, A = dat_obs$A, Q_A, Q_0, Q_1)\ndat_tmle %>%\n  head() %>%\n  gt() %>%\n  tab_header(\"TMLE Algorithm after Step 1\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"wqrrijfakd\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#wqrrijfakd .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wqrrijfakd .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wqrrijfakd .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wqrrijfakd .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wqrrijfakd .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wqrrijfakd .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wqrrijfakd .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wqrrijfakd .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wqrrijfakd .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wqrrijfakd .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wqrrijfakd .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wqrrijfakd .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wqrrijfakd .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrrijfakd .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wqrrijfakd .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wqrrijfakd .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrrijfakd .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wqrrijfakd .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrrijfakd .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wqrrijfakd .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrrijfakd .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wqrrijfakd .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wqrrijfakd .gt_left {\n  text-align: left;\n}\n\n#wqrrijfakd .gt_center {\n  text-align: center;\n}\n\n#wqrrijfakd .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wqrrijfakd .gt_font_normal {\n  font-weight: normal;\n}\n\n#wqrrijfakd .gt_font_bold {\n  font-weight: bold;\n}\n\n#wqrrijfakd .gt_font_italic {\n  font-style: italic;\n}\n\n#wqrrijfakd .gt_super {\n  font-size: 65%;\n}\n\n#wqrrijfakd .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#wqrrijfakd .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wqrrijfakd .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wqrrijfakd .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wqrrijfakd .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wqrrijfakd .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wqrrijfakd .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  <thead class=\"gt_header\">\n    <tr>\n      <td colspan=\"5\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>TMLE Algorithm after Step 1</td>\n    </tr>\n    \n  </thead>\n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Y</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">A</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Q_A</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Q_0</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Q_1</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0.8461853</td>\n<td class=\"gt_row gt_right\">0.6770917</td>\n<td class=\"gt_row gt_right\">0.8461853</td></tr>\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">0.6986440</td>\n<td class=\"gt_row gt_right\">0.6986440</td>\n<td class=\"gt_row gt_right\">0.8589257</td></tr>\n    <tr><td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">0.4932538</td>\n<td class=\"gt_row gt_right\">0.4932538</td>\n<td class=\"gt_row gt_right\">0.7188934</td></tr>\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0.8213403</td>\n<td class=\"gt_row gt_right\">0.6363132</td>\n<td class=\"gt_row gt_right\">0.8213403</td></tr>\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">0.6266258</td>\n<td class=\"gt_row gt_right\">0.6266258</td>\n<td class=\"gt_row gt_right\">0.8151742</td></tr>\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0.8578239</td>\n<td class=\"gt_row gt_right\">0.6966588</td>\n<td class=\"gt_row gt_right\">0.8578239</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n<!-- *Also note that our expected outcomes are on the original outcome scale (i.e. probability, rather than the $logit$ probability).* -->\n\nWe could stop here and get our estimate of the ATE by computing the average difference between $\\mathrm{\\hat{E}}[Y|A=1,\\mathbf{W}]$ and $\\mathrm{\\hat{E}}[Y|A=0,\\mathbf{W}]$, which *would* be the mean difference in the expected outcomes, conditional on confounders. This estimation method is often called **standardization**, **simple substitution estimation**, **g-formula estimation**, or **G-computation**.\n\n$$\\hat{ATE}_{G-comp}= \\hat{\\Psi}_{G-comp} = \\frac{1}{N}\\sum_{i=1}^{N}(\\mathrm{\\hat{E}}[Y|A=1,\\mathbf{W}]-\\mathrm{\\hat{E}}[Y|A=0,\\mathbf{W}])$$ ![](/img/tmle/ate_gcomp.png){width=\"50%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nate_gcomp <- mean(dat_tmle$Q_1 - dat_tmle$Q_0)\nate_gcomp\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.195287\n```\n:::\n:::\n\n\nHowever, this G-computation ATE estimate does not have the appropriate bias-variance tradeoff for the ATE because it was built to have the best bias-variance tradeoff for estimating the *outcome*, conditional on confounders, rather than the ATE. We also cannot compute the standard error of the estimator because we don't know the sampling distribution of the machine learning estimates.\n\n⤴️[*Back to the top*](#part-ii-the-algorithm)\n\n## Step 2: Estimate the Probability of Treatment {#step-2-estimate-the-probability-of-treatment}\n\nThe next step is to estimate the probability of treatment, given confounders. This quantity is often called the **propensity score**, as in it gives the probability or *propensity* that an observation will receive a treatment of interest.\n\n$$g(\\mathbf{W}) = \\mathrm{Pr}(A=1|\\mathbf{W})$$ ![](/img/tmle/6_treatment_fit.png){width=\"60%\"}\n\nWe will estimate $\\mathrm{Pr}(A=1|\\mathbf{W})$ in the same way as we estimated $\\mathrm{E}[Y|A,\\mathbf{W}]$: using the superlearner algorithm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA <- dat_obs$A\nW <- dat_obs %>% select(-Y, -A) # matrix of predictors that only contains the confounders W1, W2, W3, and W4\ng <- SuperLearner(Y = A, # outcome is the A (treatment) vector\n                  X = W, # W is a matrix of predictors\n                  family=binomial(), # treatment is a binomial outcome\n                  SL.library=sl_libs) # using same candidate learners; could use different learners\n```\n:::\n\n\nThen we need to compute three different quantities from this model fit:\n\n**1. The inverse probability of receiving treatment.**\n\n$$H(1,\\mathbf{W}) = \\frac{1}{g(\\mathbf{W})} = \\frac{1}{\\mathrm{Pr}(A=1|\\mathbf{W})}$$ We can estimate the probability of receiving treatment for every observation by using the `predict()` funcion without specifying any new data, and then take the inverse of that.\n\n![](/img/tmle/7_H1.png){width=\"60%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ng_w <- as.vector(predict(g)$pred) # Pr(A=1|W)\nH_1 <- 1/g_w\n```\n:::\n\n\n**2. The negative inverse probability of not receiving treatment.**\n\n$$H(0,\\mathbf{W}) = -\\frac{1}{1-g(\\mathbf{W})}= -\\frac{1}{\\mathrm{Pr}(A=0|\\mathbf{W})}$$ The probability of not receiving treatment for a binary treatment is simply 1 minus the probability of treatment.\n\n![](/img/tmle/8_H0.png){width=\"70%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nH_0 <- -1/(1-g_w) # Pr(A=0|W) is 1-Pr(A=1|W)\n```\n:::\n\n\n**3. If the observation was treated, the inverse probability of receiving treatment, and if they were not treated, the negative inverse probability of not receiving treatment.** I'll discuss why later, but in the TMLE literature this is called the **clever covariate**.\n\n$$H(A,\\mathbf{W}) = \\frac{\\mathrm{I}(A=1)}{\\mathrm{Pr}(A=1|\\mathbf{W})}-\\frac{\\mathrm{I}(A=0)}{\\mathrm{Pr}(A=0|\\mathbf{W})}$$\n\n![](/img/tmle/9_HA.png){width=\"50%\"}\n\nTo calculate the clever covariate, we'll first add the $H(1,\\mathbf{W})$ and $H(0,\\mathbf{W})$ vectors to our `dat_tmle` data frame, and then we can use $A$ to assign $H(A,\\mathbf{W})$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_tmle <- # add clever covariate data to dat_tmle\n  dat_tmle %>%\n  bind_cols(\n         H_1 = H_1,\n         H_0 = H_0) %>%\n  mutate(H_A = case_when(A == 1 ~ H_1, # if A is 1 (treated), assign H_1\n                       A == 0 ~ H_0))  # if A is 0 (not treated), assign H_0\n```\n:::\n\n\nWe now have our initial estimates of the outcome, and the estimates of the probability of treatment:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_tmle %>% head() %>% gt() %>% tab_header(\"TMLE Algorithm after Step 2\") %>% fmt_number(everything(), decimals = 2)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"hjkpoiqvpu\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#hjkpoiqvpu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hjkpoiqvpu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hjkpoiqvpu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hjkpoiqvpu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hjkpoiqvpu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hjkpoiqvpu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hjkpoiqvpu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hjkpoiqvpu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hjkpoiqvpu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hjkpoiqvpu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hjkpoiqvpu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hjkpoiqvpu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hjkpoiqvpu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjkpoiqvpu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hjkpoiqvpu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hjkpoiqvpu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjkpoiqvpu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hjkpoiqvpu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjkpoiqvpu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hjkpoiqvpu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjkpoiqvpu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hjkpoiqvpu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hjkpoiqvpu .gt_left {\n  text-align: left;\n}\n\n#hjkpoiqvpu .gt_center {\n  text-align: center;\n}\n\n#hjkpoiqvpu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hjkpoiqvpu .gt_font_normal {\n  font-weight: normal;\n}\n\n#hjkpoiqvpu .gt_font_bold {\n  font-weight: bold;\n}\n\n#hjkpoiqvpu .gt_font_italic {\n  font-style: italic;\n}\n\n#hjkpoiqvpu .gt_super {\n  font-size: 65%;\n}\n\n#hjkpoiqvpu .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#hjkpoiqvpu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hjkpoiqvpu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hjkpoiqvpu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hjkpoiqvpu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hjkpoiqvpu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hjkpoiqvpu .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  <thead class=\"gt_header\">\n    <tr>\n      <td colspan=\"8\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>TMLE Algorithm after Step 2</td>\n    </tr>\n    \n  </thead>\n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Y</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">A</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Q_A</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Q_0</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">Q_1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">H_1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">H_0</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">H_A</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">1.00</td>\n<td class=\"gt_row gt_right\">1.00</td>\n<td class=\"gt_row gt_right\">0.85</td>\n<td class=\"gt_row gt_right\">0.68</td>\n<td class=\"gt_row gt_right\">0.85</td>\n<td class=\"gt_row gt_right\">2.18</td>\n<td class=\"gt_row gt_right\">−1.85</td>\n<td class=\"gt_row gt_right\">2.18</td></tr>\n    <tr><td class=\"gt_row gt_right\">1.00</td>\n<td class=\"gt_row gt_right\">0.00</td>\n<td class=\"gt_row gt_right\">0.70</td>\n<td class=\"gt_row gt_right\">0.70</td>\n<td class=\"gt_row gt_right\">0.86</td>\n<td class=\"gt_row gt_right\">1.60</td>\n<td class=\"gt_row gt_right\">−2.67</td>\n<td class=\"gt_row gt_right\">−2.67</td></tr>\n    <tr><td class=\"gt_row gt_right\">0.00</td>\n<td class=\"gt_row gt_right\">0.00</td>\n<td class=\"gt_row gt_right\">0.49</td>\n<td class=\"gt_row gt_right\">0.49</td>\n<td class=\"gt_row gt_right\">0.72</td>\n<td class=\"gt_row gt_right\">3.39</td>\n<td class=\"gt_row gt_right\">−1.42</td>\n<td class=\"gt_row gt_right\">−1.42</td></tr>\n    <tr><td class=\"gt_row gt_right\">1.00</td>\n<td class=\"gt_row gt_right\">1.00</td>\n<td class=\"gt_row gt_right\">0.82</td>\n<td class=\"gt_row gt_right\">0.64</td>\n<td class=\"gt_row gt_right\">0.82</td>\n<td class=\"gt_row gt_right\">2.39</td>\n<td class=\"gt_row gt_right\">−1.72</td>\n<td class=\"gt_row gt_right\">2.39</td></tr>\n    <tr><td class=\"gt_row gt_right\">1.00</td>\n<td class=\"gt_row gt_right\">0.00</td>\n<td class=\"gt_row gt_right\">0.63</td>\n<td class=\"gt_row gt_right\">0.63</td>\n<td class=\"gt_row gt_right\">0.82</td>\n<td class=\"gt_row gt_right\">2.31</td>\n<td class=\"gt_row gt_right\">−1.76</td>\n<td class=\"gt_row gt_right\">−1.76</td></tr>\n    <tr><td class=\"gt_row gt_right\">1.00</td>\n<td class=\"gt_row gt_right\">1.00</td>\n<td class=\"gt_row gt_right\">0.86</td>\n<td class=\"gt_row gt_right\">0.70</td>\n<td class=\"gt_row gt_right\">0.86</td>\n<td class=\"gt_row gt_right\">2.14</td>\n<td class=\"gt_row gt_right\">−1.88</td>\n<td class=\"gt_row gt_right\">2.14</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n⤴️[*Back to the top*](#part-ii-the-algorithm)\n\n## Step 3: Estimate the Fluctuation Parameter {#step-3-estimate-the-fluctuation-parameter}\n\nTo reiterate, in [Step 1](#step-1-estimate-the-outcome) we estimated the expected outcome, conditional on treatment and confounders. We know those machine learning fits have an optimal bias-variance trade-off for estimating the outcome (conditional on treatment and confounders), rather than the ATE. **We will now use information about the treatment mechanism (from Step 2) to optimize the bias-variance trade-off for the ATE so we can obtain valid inference.**\n\n<html>\n\n<head>\n\n<title>HTML Image as link</title>\n\n</head>\n\n<body><a href=\"\"> <img src=\"/img/bear_with_me.jpg\" alt=\"cheatsheet\" style=\"float:right; padding-left:65px;\" width=\"50%&quot;\"/> </a></body>\n\n</html>\n\n🚨 ***Warning:*** this step is easy to code, but difficult to understand unless you have a background in semiparametric theory. Let's first look at *what* we're doing, and then I'll discuss at a very high-level why we're doing that in a [later section](https://khstats.com/blog/tmle/tutorial-pt3/#why-does-tmle-work).\n\nThe point of this step is to solve an *estimating equation* for the *efficient influence function* (EIF) of our estimand of interest. Without diving into what an EIF or an estimating equation is, let's accept for a moment that they will help us:\n\n1.  **Update our initial outcome estimates** so that our estimate of the ATE is asymptotically unbiased (under certain conditions, see [*Part III, Statistical Properties*](https://khstats.com/blog/tmle/tutorial-pt3/#properties-of-tmle)).\n\n2.  **Calculate the variance**, and thus the standard error, confidence interval, and p-value for our estimate of the ATE for hypothesis testing.\n\nNext, let's take a look at a model that will help us solve an EIF estimating equation and then update our estimates:\n\n$$logit(\\mathrm{E}[Y|A,\\mathbf{W}]) = logit(\\mathrm{\\hat{E}}[Y|A,\\mathbf{W}]) + \\epsilon H(A,\\mathbf{W})$$\n\nTo reiterate, I haven't explained at all why this step works; we're just focusing on implementing it for now.\n\nIf we look at the left side, we can see this equation contains the true outcome $Y$, just $logit$ transformed. Luckily for us, there's a well-known model that $logit$ transforms the left side of an equation: logistic regression. Our estimating equation looks *a lot* like a simple logistic regression, actually: $logit(\\mathrm{E}[Y|X]) = \\beta_0 + \\beta_1 X$.\n\nDo you see how our equation also has a vector on the right-hand side, $H(A,\\mathbf{W})$, with a corresponding coefficient, $\\epsilon$? The only difference is that the \"intercept\" in our equation, $logit(\\mathrm{\\hat{E}}[Y|A,\\mathbf{W}])$ is not a constant value like $\\beta_0$; it is a vector of values. We can see it as an **offset** or a **fixed intercept** in a logistic regression, rather than a constant-value intercept.\n\nTherefore, to accomplish our goal of solving an estimating equation for the EIF we can leverage standard statistical software and fit a logistic regression with one covariate, $H(A,\\mathbf{W})$, and the initial outcome estimate, $logit(\\mathrm{\\hat{E}}[Y|A,\\mathbf{W}])$, as a fixed intercept. The outcome of the logistic regression is the observed outcome, $Y$.\n\nTwo technical points for application: we use `qlogis` to transform the probabilities $\\mathrm{\\hat{E}}[Y|A,\\mathbf{W}]$ to the $logit$ scale. Also, the `R` code for a fixed intercept is `-1 + offset(fixed_intercept)`.\n\n![](/img/tmle/10_logistic_regression.png)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglm_fit <- glm(Y ~ -1 + offset(qlogis(Q_A)) + H_A, data=dat_tmle, family=binomial)\n```\n:::\n\n\n*Note that we are only using a logistic regression because it happens to have the correct form for solving the estimating equation for the EIF for the ATE estimand. It has nothing to do with having a binary outcome, and it isn't putting any parametric restraints on our data.*\n\nNext we need to save the coefficient from that logistic regression, which we will call $\\hat{\\epsilon}$:\n\n![](/img/tmle/11_epsilon.png){width=\"40%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\neps <- coef(glm_fit)\n```\n:::\n\n\nIn the TMLE literature, $\\epsilon$ is called the **fluctuation parameter**, because it provides information about how much to change, or fluctuate, our initial outcome estimates. Similarly, $H(A,\\mathbf{W})$ is called the **clever covariate** because it \"cleverly\" helps us solve for the EIF and then update our estimates.\n\nWe will use both the fluctuation parameter and clever covariate in the next step to update our initial estimates of the expected outcome, conditional on confounders and treatment.\n\n⤴️[*Back to the top*](#part-ii-the-algorithm)\n\n## Step 4: Update the Initial Estimates of the Expected Outcome {#step-4-update-the-initial-estimates-of-the-expected-outcome}\n\nAlmost done! Let's recap:\n\n-   In [Step 1](#estimate-the-outcome), we obtained **initial estimates** of the expected outcome using machine learning (ML). These ML estimates are optimized to estimate $E[Y|A,W]$, not the ATE.\n\n-   We need to update those initial expected outcome estimates using **information about the treatment mechanism**, so we computed the expected probability of treatment, conditional on confounders, in [Step 2](#estimate-the-probability-of-treatment).\n\n-   Then, in [Step 3](#estimate-the-fluctuation-parameter), we used quantities from Step 1 and Step 2 to **solve an estimating equation for the EIF**. We didn't talk about *why* this works; we simply accepted for now that this is how we can target our estimand of interest (the ATE).\n\n-   Now, we will **update our initial outcome estimates** from Step 1 using information from Step 2 and 3 to obtain the correct bias-variance tradeoff for the ATE.\n\nTo update our expected outcome estimates, we first need to **put the initial expected outcome estimates on the** $logit$ scale using `qlogis()` because that's the scale we used to solve our estimating equation for the EIF in Step 3. Then we can **calculate how much we need to fluctuate our initial estimates** using the product of the clever covariate and fluctuation parameter: $H(A,\\mathbf{W}) \\times \\hat{\\epsilon}$. These are our outputs of Step 2 and 3, respectively. We will **add that quantity to the initial outcome estimates to create updated outcome estimates**. Finally, we can **put the updated estimates back on the true outcome scale** using `plogis()`.\n\n*Note we can use* $expit$ to show the inverse of the $logit$ function, and we will denote updates to the outcome regressions as $\\hat{\\mathrm{E}}^*$ instead of $\\hat{\\mathrm{E}}$.\n\n**1. Update the expected outcomes of all observations, given the treatment they actually received and their baseline confounders.**\n\n$$\\hat{\\mathrm{E}}^*[Y|A,\\mathbf{W}] = expit(logit(\\mathrm{\\hat{E}}[Y|A,\\mathbf{W}]) + \\hat{\\epsilon}H(A,\\mathbf{W}))$$\n\n![](/img/tmle/update_qAW.png){width=\"70%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nH_A <- dat_tmle$H_A # for cleaner code in Q_A_update\nQ_A_update <- plogis(qlogis(Q_A) + eps*H_A)\n```\n:::\n\n\n**2. Update the expected outcomes, conditional on baseline confounders and everyone receiving the treatment.**\n\n$$\\hat{\\mathrm{E}}^*[Y|A=1,\\mathbf{W}] = expit(logit(\\mathrm{\\hat{E}}[Y|A=1,\\mathbf{W}]) + \\hat{\\epsilon}H(1,A))$$ ![](/img/tmle/12_update_Q1.png){width=\"70%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ_1_update <- plogis(qlogis(Q_1) + eps*H_1)\n```\n:::\n\n\n**3. Update the expected outcomes, conditional on baseline confounders and no one receiving the treatment.**\n\n$$\\hat{\\mathrm{E}}^*[Y|A=0,\\mathbf{W}] = expit(logit(\\mathrm{\\hat{E}}[Y|A=0,\\mathbf{W}]) + \\hat{\\epsilon}H(0,W))$$ ![](/img/tmle/13_update_Q0.png){width=\"70%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nQ_0_update <- plogis(qlogis(Q_0) + eps*H_0)\n```\n:::\n\n\n⤴️[*Back to the top*](#part-ii-the-algorithm)\n\n## Step 5: Compute the Statistical Estimand of Interest {#step-5-compute-the-statistical-estimand-of-interest}\n\nWe now have updated expected outcomes estimates, so we can **compute the ATE as the mean difference in the updated outcome estimates under treatment and no treatment**:\n\n$$\\hat{ATE}_{TMLE} = \\hat{\\Psi}_{TMLE} = \\frac{1}{N}\\sum_{i=1}^{N}[\\hat{E^*}[Y|A=1,\\mathbf{W}] - \\hat{E^*}[Y|A=0,\\mathbf{W}]]$$\n\n![](/img/tmle/14_compute_ATE.png){width=\"60%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmle_ate <- mean(Q_1_update - Q_0_update)\ntmle_ate\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1911676\n```\n:::\n:::\n\n\nWe can then say, \"the average treatment effect was estimated to be 19.1%.\"\n\nIf causal assumptions were not met, we would say, \"the proportion of observations who experienced the outcome, after adjusting for baseline confounders, was estimated to be 19.1% higher for those who received treatment compared to those who did not.\"\n\n⤴️[*Back to the top*](#part-ii-the-algorithm)\n\n## Step 6: Calculate the Standard Errors for Confidence Intervals and P-values {#step-6-calculate-the-standard-errors-for-confidence-intervals-and-p-values}\n\nThis point estimate is great, but we usually need an **estimate of variance** so that we can compute confidence intervals, test statistics, p-values, etc. This is another step that contains quite a lot of theory, so I'll give another birds-eye view for now. If you're curious, you can read more about this in [*Part III*](https://khstats.com/blog/tmle/tutorial-pt3).\n\nTo obtain the standard errors, we first need to compute the **Influence Function** (IF), which is the empirical version of what we used our estimating equation to figure out in [Step 3](#step-3-estimate-the-fluctuation-parameter). The IF tells us **how much each observation influences the final estimate**.\n\nThe equation for the IF looks like this:\n\n$$\\hat{IF} = (Y-\\hat{E^*}[Y|A,\\mathbf{W}])H(A,\\mathbf{W}) + \\hat{E^*}[Y|A=1,\\mathbf{W}] - \\hat{E^*}[Y|A=0,\\mathbf{W}] - \\hat{ATE}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfl_fn <- (Y - Q_A_update) * H_A + Q_1_update - Q_0_update - tmle_ate\n```\n:::\n\n\nOnce we have the IF, we can **take the square-root of its variance divided by the number of observations** to get the standard error of our estimate.\n\n$$\\hat{SE} = \\sqrt{\\frac{var(\\hat{IF})}{N}} $$\n\n![](/img/tmle/15_ses.png){width=\"100%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmle_se <- sqrt(var(infl_fn)/nrow(dat_obs))\n```\n:::\n\n\nOnce we have that standard error, we can easily get the 95% confidence interval and p-value of our estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconf_low <- tmle_ate - 1.96*tmle_se\nconf_high <- tmle_ate + 1.96*tmle_se\npval <- 2 * (1 - pnorm(abs(tmle_ate / tmle_se)))\n\ntibble(tmle_ate, conf_low, conf_high) %>% head() %>% gt() %>% tab_header(\"TMLE Estimate of the ATE\") %>% fmt_number(everything(), decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"hrilomjnxp\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#hrilomjnxp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#hrilomjnxp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#hrilomjnxp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#hrilomjnxp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#hrilomjnxp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#hrilomjnxp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#hrilomjnxp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#hrilomjnxp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hrilomjnxp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#hrilomjnxp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#hrilomjnxp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#hrilomjnxp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#hrilomjnxp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrilomjnxp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#hrilomjnxp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#hrilomjnxp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrilomjnxp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#hrilomjnxp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrilomjnxp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#hrilomjnxp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrilomjnxp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#hrilomjnxp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#hrilomjnxp .gt_left {\n  text-align: left;\n}\n\n#hrilomjnxp .gt_center {\n  text-align: center;\n}\n\n#hrilomjnxp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#hrilomjnxp .gt_font_normal {\n  font-weight: normal;\n}\n\n#hrilomjnxp .gt_font_bold {\n  font-weight: bold;\n}\n\n#hrilomjnxp .gt_font_italic {\n  font-style: italic;\n}\n\n#hrilomjnxp .gt_super {\n  font-size: 65%;\n}\n\n#hrilomjnxp .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#hrilomjnxp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#hrilomjnxp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#hrilomjnxp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#hrilomjnxp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#hrilomjnxp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#hrilomjnxp .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  <thead class=\"gt_header\">\n    <tr>\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>TMLE Estimate of the ATE</td>\n    </tr>\n    \n  </thead>\n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">tmle_ate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">conf_low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">conf_high</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">0.191</td>\n<td class=\"gt_row gt_right\">0.133</td>\n<td class=\"gt_row gt_right\">0.249</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nThen we can successfully report our ATE as 0.191 (95% CI: 0.133, 0.249).\n\n*Note that a TMLE estimator is asymptotically normally distributed, so we could bootstrap the entire algorithm to get our standard errors instead.*\n\n⤴️[*Back to the top*](#part-ii-the-algorithm)\n\n# Using the `tmle` package 📦 {#using-the-tmle-package}\n\nLuckily there are `R` packages so that you don't have to hand code TMLE yourself. `R` packages to implement the TMLE algorithm include [`tmle`](https://www.jstatsoft.org/article/view/v051i13), [`tmle3`](https://tlverse.org/tlverse-handbook/tmle3.html), [`ltmle`](https://www.jstatsoft.org/article/view/v081i01), [`drtmle`](https://cran.r-project.org/web/packages/drtmle/vignettes/using_drtmle.html), and [`lmtp`](https://htmlpreview.github.io/?https://gist.githubusercontent.com/nt-williams/ddd44c48390b8d976fad71750e48d8bf/raw/45db700a02bf92e2a55790e60ed48266a97ca4e7/intro-lmtp.html).\n\nThe code using the original `tmle` package's `tmle()` function is:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmle_fit <-\n  tmle::tmle(Y = Y, # outcome vector\n           A = A, # treatment vector\n           W = W, # matrix of confounders W1, W2, W3, W4\n           Q.SL.library = sl_libs, # superlearning libraries from earlier for outcome regression Q(A,W)\n           g.SL.library = sl_libs) # superlearning libraries from earlier for treatment regression g(W)\n\ntmle_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Additive Effect\n   Parameter Estimate:  0.19188\n   Estimated Variance:  0.00088096\n              p-value:  1.0142e-10\n    95% Conf Interval: (0.13371, 0.25006) \n\n Additive Effect among the Treated\n   Parameter Estimate:  0.18992\n   Estimated Variance:  0.00091243\n              p-value:  3.2259e-10\n    95% Conf Interval: (0.13072, 0.24913) \n\n Additive Effect among the Controls\n   Parameter Estimate:  0.19372\n   Estimated Variance:  0.00101\n              p-value:  1.0908e-09\n    95% Conf Interval: (0.13143, 0.25601) \n```\n:::\n:::\n\n\nWe can get the same result (variation due to randomness in the machine learning models) in just a few lines of code: the estimate using the original `tmle` package is 0.192 (95% CI: 0.134, 0.25).\n\n------------------------------------------------------------------------\n\nTo learn more about the statistical properties of TMLE and the underlying theory, [*continue on to Part III*](https://khstats.com/blog/tmle/tutorial-pt3). Alternatively, return to the motivation in [*Part I*](https://khstats.com/blog/tmle/tutorial/), or see the full tutorial code below.\n\n\n------------------------------------------------------------------------\n\n# Full tutorial code {#full-tutorial-code}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) # for data manipulation\nlibrary(SuperLearner) # for ensemble learning\n\nset.seed(7) # for reproducible results\n\nsl_libs <- c('SL.glmnet', 'SL.ranger', 'SL.earth') # a library of machine learning algorithms (penalized regression, random forests, and multivariate adaptive regression splines)\n\ngenerate_data <- function(n){ \n    W1 <- rbinom(n, size=1, prob=0.2) # binary confounder\n    W2 <- rbinom(n, size=1, prob=0.5) # binary confounder\n    W3 <- round(runif(n, min=2, max=7)) # continuous confounder\n    W4 <- round(runif(n, min=0, max=4)) # continuous confounder\n    A  <- rbinom(n, size=1, prob= plogis(-0.2 + 0.2*W2 + log(0.1*W3) + 0.3*W4 + 0.2*W1*W4)) # binary treatment depends on confounders\n    Y <- rbinom(n, size=1, prob= plogis(-1 + A - 0.1*W1 + 0.2*W2 + 0.3*W3 - 0.1*W4 + sin(0.1*W2*W4))) # binary outcome depends on confounders\n    return(tibble(Y, W1, W2, W3, W4, A))\n}\n\nn <- 1000\ndat_obs <- generate_data(n) # generate a data set with n observations\n\nY <- dat_obs$Y\nW_A <- dat_obs %>% select(-Y) # remove the outcome to make a matrix of predictors (A, W1, W2, W3, W4) for SuperLearner\n\n### Step 1: Estimate Q\nQ <- SuperLearner(Y = Y, # Y is the outcome vector\n                  X = W_A, # W_A is the matrix of W1, W2, W3, W4, and A\n                  family=binomial(), # specify we have a binary outcome\n                  SL.library = sl_libs) # specify our superlearner library of LASSO, RF, and MARS\nQ_A <- as.vector(predict(Q)$pred) # obtain predictions for everyone using the treatment they actually received\nW_A1 <- W_A %>% mutate(A = 1)  # data set where everyone received treatment\nQ_1 <- as.vector(predict(Q, newdata = W_A1)$pred) # predict on that everyone-exposed data set\nW_A0 <- W_A %>% mutate(A = 0) # data set where no one received treatment\nQ_0 <- as.vector(predict(Q, newdata = W_A0)$pred)\ndat_tmle <- tibble(Y = dat_obs$Y, A = dat_obs$A, Q_A, Q_0, Q_1)\n\n### Step 2: Estimate g and compute H(A,W)\nA <- dat_obs$A\nW <- dat_obs %>% select(-Y, -A) # matrix of predictors that only contains the confounders W1, W2, W3, and W4\ng <- SuperLearner(Y = A, # outcome is the A (treatment) vector\n                  X = W, # W is a matrix of predictors\n                  family=binomial(), # treatment is a binomial outcome\n                  SL.library=sl_libs) # using same candidate learners; could use different learners\n\ng_w <- as.vector(predict(g)$pred) # Pr(A=1|W)\nH_1 <- 1/g_w\nH_0 <- -1/(1-g_w) # Pr(A=0|W) is 1-Pr(A=1|W)\ndat_tmle <- # add clever covariate data to dat_tmle\n  dat_tmle %>%\n  bind_cols(\n         H_1 = H_1,\n         H_0 = H_0) %>%\n  mutate(H_A = case_when(A == 1 ~ H_1, # if A is 1 (treated), assign H_1\n                       A == 0 ~ H_0))  # if A is 0 (not treated), assign H_0\n\n### Step 3: Estimate fluctuation parameter\nglm_fit <- glm(Y ~ -1 + offset(qlogis(Q_A)) + H_A, data=dat_tmle, family=binomial) # fixed intercept logistic regression\neps <- coef(glm_fit) # save the only coefficient, called epsilon in TMLE lit\n\n### Step 4: Update Q's\nH_A <- dat_tmle$H_A # for cleaner code in Q_A_update\nQ_A_update <- plogis(qlogis(Q_A) + eps*H_A) # updated expected outcome given treatment actually received\nQ_1_update <- plogis(qlogis(Q_1) + eps*H_1) # updated expected outcome for everyone receiving treatment\nQ_0_update <- plogis(qlogis(Q_0) + eps*H_0) # updated expected outcome for everyone not receiving treatment\n\n### Step 5: Compute ATE\ntmle_ate <- mean(Q_1_update - Q_0_update) # mean diff in updated expected outcome estimates\n\n### Step 6: compute standard error, CIs and pvals\ninfl_fn <- (Y - Q_A_update) * H_A + Q_1_update - Q_0_update - tmle_ate # influence function\ntmle_se <- sqrt(var(infl_fn)/nrow(dat_obs)) # standard error\nconf_low <- tmle_ate - 1.96*tmle_se # 95% CI\nconf_high <- tmle_ate + 1.96*tmle_se\npval <- 2 * (1 - pnorm(abs(tmle_ate / tmle_se))) # p-value at alpha .05\n\ntmle_ate\nconf_low\nconf_high\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.1.2 (2021-11-01)\nPlatform: x86_64-apple-darwin17.0 (64-bit)\nRunning under: macOS Big Sur 10.16\n\nMatrix products: default\nBLAS:   /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRblas.0.dylib\nLAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib\n\nlocale:\n[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8\n\nattached base packages:\n[1] splines   stats     graphics  grDevices utils     datasets  methods  \n[8] base     \n\nother attached packages:\n [1] SuperLearner_2.0-28 gam_1.22-2          foreach_1.5.2      \n [4] nnls_1.4            gt_0.7.0            forcats_0.5.1      \n [7] stringr_1.5.0       dplyr_1.0.10        purrr_0.3.5        \n[10] readr_2.1.2         tidyr_1.2.1         tibble_3.1.8       \n[13] ggplot2_3.4.0       tidyverse_1.3.2    \n\nloaded via a namespace (and not attached):\n [1] httr_1.4.2          sass_0.4.5          jsonlite_1.8.4     \n [4] modelr_0.1.8        Formula_1.2-4       assertthat_0.2.1   \n [7] googlesheets4_1.0.0 cellranger_1.1.0    yaml_2.3.7         \n[10] pillar_1.8.1        backports_1.4.1     lattice_0.20-45    \n[13] glue_1.6.2          digest_0.6.31       rvest_1.0.2        \n[16] colorspace_2.0-3    htmltools_0.5.4     Matrix_1.3-4       \n[19] pkgconfig_2.0.3     broom_1.0.1         earth_5.3.1        \n[22] haven_2.4.3         scales_1.2.1        ranger_0.14.1      \n[25] TeachingDemos_2.12  tzdb_0.2.0          googledrive_2.0.0  \n[28] generics_0.1.3      ellipsis_0.3.2      withr_2.5.0        \n[31] ROCR_1.0-11         cli_3.6.1           survival_3.2-13    \n[34] magrittr_2.0.3      crayon_1.5.0        readxl_1.3.1       \n[37] evaluate_0.20       fs_1.6.0            fansi_1.0.3        \n[40] xml2_1.3.3          tools_4.1.2         hms_1.1.1          \n[43] gargle_1.2.0        lifecycle_1.0.3     munsell_0.5.0      \n[46] reprex_2.0.1        glmnet_4.1-3        plotrix_3.8-2      \n[49] compiler_4.1.2      rlang_1.0.6         plotmo_3.6.1       \n[52] grid_4.1.2          iterators_1.0.14    rstudioapi_0.13    \n[55] htmlwidgets_1.5.4   rmarkdown_2.20      gtable_0.3.1       \n[58] codetools_0.2-18    DBI_1.1.2           R6_2.5.1           \n[61] lubridate_1.8.0     knitr_1.42          fastmap_1.1.0      \n[64] utf8_1.2.2          shape_1.4.6         tmle_1.5.0.2       \n[67] stringi_1.7.12      Rcpp_1.0.9          vctrs_0.5.2        \n[70] dbplyr_2.1.1        tidyselect_1.2.0    xfun_0.36          \n```\n:::\n:::\n\n\n⬅️️[*Back to Part I: Motivation*](https://khstats.com/blog/tmle/tutorial)\n\n⤴️[*Back to the top*](#part-ii-the-algorithm)\n\n➡️[*Continue to Part III:Properties, Theory, and Learning More*](https://khstats.com/blog/tmle/tutorial-pt3/)\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}