---
title: "Publications"
editor: source
---
<p style="text-align: left; margin-top: 20px;"><small>Last updated <i>September 27, 2022&ndash; Pulled automatically from my <a href="https://scholar.google.com/citations?hl=en&user=b8bWNkUAAAAJ">Google Scholar profile</a>. See <a href="https://thackl.github.io/automatically-update-publications-with-R-scholar">this post</a> for details.</small></p>
<h3>2022</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">G Waldrop, SA Safavynia, ME Barra, S Agarwal, DA Berlin, AK Boehme et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=18415137599459960440&btnI=1&hl=en">Prolonged Unconsciousness is Common in COVID‐19 and Associated with Hypoxemia</a>, Annals of neurology, </td></tr>
<tr><td width="100%">K Weidman, E LaFond, <b>KL Hoffman</b>, P Goyal, CN Parkhurst, H Derry-Vick et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8912967969137626752&btnI=1&hl=en">Post–Intensive Care Unit Syndrome in a Cohort of COVID-19 Survivors in New York City</a>, Annals of the American Thoracic Society, 19 (7), 1158-1168</td></tr>
<tr><td width="100%">DR Price, E Benedetti, <b>KL Hoffman</b>, L Gomez-Escobar, S Alvarez-Mulett et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=3454590054880761273&btnI=1&hl=en">Angiopoietin 2 is associated with vascular necroptosis induction in coronavirus disease 2019 acute respiratory distress syndrome</a>, The American journal of pathology, 192 (7), 1001-1015</td></tr>
<tr><td width="100%">MJ Satlin, L Chen, A Gomez-Simmonds, J Marino, G Weston, T Bhowmick et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=1687345112640694729&btnI=1&hl=en">Impact of a rapid molecular test for Klebsiella pneumoniae carbapenemase and ceftazidime-avibactam use on outcomes after bacteremia caused by carbapenem-resistant Enterobacterales</a>, Clinical Infectious Diseases, </td></tr>
<tr><td width="100%">M Buyukozkan, S Alvarez-Mulett, AC Racanelli, F Schmidt, R Batra et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=5644024782133605865,729237390876530969&btnI=1&hl=en">Integrative Metabolomic and Proteomic Signatures Define Clinical Outcomes in Severe COVID-19</a>, medRxiv, 2021.07. 19.21260776</td></tr>
<tr><td width="100%">X Wu, Y Jeong, SP de Frías, I Easthausen, <b>K Hoffman</b>, C Oromendia et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10727101649116519068&btnI=1&hl=en">Serum proteomic profiling of rheumatoid arthritis–interstitial lung disease with a comparison to idiopathic pulmonary fibrosis</a>, Thorax, 77 (10), 1041-1044</td></tr>
<tr><td width="100%">I Díaz, <b>KL Hoffman</b>, NS Hejazi (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11430395625261655312&btnI=1&hl=en">Causal survival analysis under competing risks using longitudinal modified treatment policies</a>, arXiv preprint arXiv:, :2202.03513</td></tr>
<tr><td width="100%">JI Basem, AF Roth, RS White, VE Tangel, SY Jiang, JM Choi, <b>KL Hoffman</b> et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Patient care in rapid-expansion intensive care units during the COVID-19 pandemic crisis</a>, BMC anesthesiology, 22 (1), 1-11</td></tr>
<tr><td width="100%">R Batra, W Whalen, S Alvarez-Mulett, LG Gomez-Escobar, <b>KL Hoffman</b> et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Multi-omic comparative analysis of COVID-19 and bacterial sepsis-induced ARDS</a>, PLoS pathogens, 18 (9), e1010819</td></tr>
<tr><td width="100%">JK Krishnan, M Rajan, BR Baer, <b>KL Hoffman</b>, MN Alshak, KI Aronson et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Assessing mortality differences across acute respiratory failure management strategies in Covid-19</a>, Journal of Critical Care, 70, 154045</td></tr>
<tr><td width="100%">E Coskun, R Kalil, A Yin, G Wehmeyer, <b>K Hoffman</b>, R Kopparam et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Choices and Outcomes of the Oldest Old Admitted During the First Wave of COVID-19 in New York City</a>, Journal of Palliative Care, 08258597221098130</td></tr>
<tr><td width="100%">K Crane, J Choi, JK Krishnan, D Pan, L Lief, <b>K Hoffman</b>, P Goyal et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Association Between 28-Day Mortality and Cumulative Hospital Caseloads During the First COVID-19 Surge</a>, D, D21. RISK FACTORS AND PREDICTORS IN CRITICAL ILLNESS AND CHRONIC RESPIRATORY …</td></tr>
<tr><td width="100%">WZ Zhang, W Simmons, K Kim, <b>K Hoffman</b>, D Redmond et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Hyperferritinemia in COVID-19: A Mechanistic Role for Macrophage Ferritin in Acute Respiratory Distress Syndrome</a>, D, D97. MACROPHAGES AND INFLAMMATION IN ACUTE LUNG INJURY, A5308-A5308</td></tr>
<tr><td width="100%">JK Krishnan, KM Ancy, C Oromendia, <b>KL Hoffman</b>, I Easthausen et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Characterizing COPD Symptom Variability in the Stable State Utilizing the Evaluating Respiratory Symptoms in COPD Questionnaire.</a>, Chronic Obstructive Pulmonary Diseases (Miami, Fla.), </td></tr>
<tr><td width="100%"><b>K Hoffman</b>, E Schenck, MJ Satlin, W Whalen, D Pan, N Williams, I Diaz (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Corticosteroids in COVID-19: Optimizing Observational Research through Target Trial Emulations (preprint)</a>, , </td></tr>
<tr><td width="100%">R Batra, W Whalen, S Alvarez-Mulett, <b>K Hoffman</b>, W Simmons et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Multi-omic comparative analysis of COVID-19 and bacterial sepsis-induced ARDS (preprint)</a>, , </td></tr>
<tr><td width="100%">K Weidman, E LaFond, <b>KL Hoffman</b>, P Goyal, CN Parkhurst, H Derry-Vick et al. (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Post-Intensive Care Unit Syndrome in a Cohort of COVID-19 Survivors in New York City.</a>, Ann Am Thorac Soc, 1158-1168</td></tr>
<tr><td width="100%"><b>KL Hoffman</b>, EJ Schenck, M Satlin, W Whalen, D Pan, N Williams, I Díaz (2022) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Corticosteroids in COVID-19: Optimizing Observational Research through Target Trial Emulations</a>, medRxiv, </td></tr>
</tbody></table>
<h3>2021</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">M Reiterer, M Rajan, N Gómez-Banoy, JD Lau, LG Gomez-Escobar, L Ma et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8602263084799433155&btnI=1&hl=en">Hyperglycemia in acute COVID-19 is characterized by insulin resistance and adipose tissue infectivity by SARS-CoV-2</a>, Cell metabolism, 33 (11), 2174-2188. e5</td></tr>
<tr><td width="100%">I Díaz, N Williams, <b>KL Hoffman</b>, EJ Schenck (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12187169921591853998&btnI=1&hl=en">Nonparametric causal effects based on longitudinal modified treatment policies</a>, Journal of the American Statistical Association, 1-16</td></tr>
<tr><td width="100%">C Su, Z Xu, <b>K Hoffman</b>, P Goyal, MM Safford, J Lee, S Alvarez-Mulett et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12280450816091455915&btnI=1&hl=en">Identifying organ dysfunction trajectory-based subphenotypes in critically ill patients with COVID-19</a>, Scientific Reports, 11 (1), 1-13</td></tr>
<tr><td width="100%">EJ Schenck, <b>KL Hoffman</b>, M Cusick, J Kabariti, ET Sholle, TR Campion Jr (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10331838660527552439&btnI=1&hl=en">Critical carE Database for Advanced Research (CEDAR): An automated method to support intensive care units with electronic health record data</a>, Journal of Biomedical Informatics, 118, 103789</td></tr>
<tr><td width="100%">LG Gómez-Escobar, <b>KL Hoffman</b>, JJ Choi, A Borczuk, S Salvatore et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=18009670318072954063&btnI=1&hl=en">Cytokine signatures of end organ injury in COVID-19</a>, Scientific reports, 11 (1), 1-15</td></tr>
<tr><td width="100%">M Reiterer, M Rajan, N Gómez-Banoy, JD Lau, LG Gomez-Escobar et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=18210316204104662355&btnI=1&hl=en">Hyperglycemia in acute COVID-19 is characterized by adipose tissue dysfunction and insulin resistance</a>, MedRxiv, </td></tr>
<tr><td width="100%">U Khan, K Ho, EK Hwang, C Peña, J Brouwer, <b>K Hoffman</b>, D Betel et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10892417320702125758&btnI=1&hl=en">Impact of use of antibiotics on response to immune checkpoint inhibitors and tumor microenvironment</a>, American Journal of Clinical Oncology, 44 (6), 247-253</td></tr>
<tr><td width="100%">LK Torres, <b>KL Hoffman</b>, C Oromendia, I Diaz, JS Harrington, EJ Schenck et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=2060365820737663153&btnI=1&hl=en">Attributable mortality of acute respiratory distress syndrome: a systematic review, meta-analysis and survival analysis using targeted minimum loss-based estimation</a>, Thorax, 76 (12), 1176-1185</td></tr>
<tr><td width="100%">DR Price, <b>KL Hoffman</b>, C Oromendia, LK Torres, EJ Schenck, ME Choi et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=2822350090363222773&btnI=1&hl=en">Effect of neutropenic critical illness on development and prognosis of acute respiratory distress syndrome</a>, American journal of respiratory and critical care medicine, 203 (4), 504-508</td></tr>
<tr><td width="100%">WZ Zhang, <b>KL Hoffman</b>, KT Schiffer, C Oromendia, MC Rice et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=12423034351317135285&btnI=1&hl=en">Association of plasma mitochondrial DNA with COPD severity and progression in the SPIROMICS cohort</a>, Respiratory research, 22 (1), 1-11</td></tr>
<tr><td width="100%">EJ Schenck, <b>KL Hoffman</b>, C Oromendia, E Sanchez, EJ Finkelsztein et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8550221426624105951&btnI=1&hl=en">A comparative analysis of the respiratory subscore of the sequential organ failure assessment scoring system</a>, Annals of the American Thoracic Society, 18 (11), 1849-1860</td></tr>
<tr><td width="100%">E Mauer, J Lee, J Choi, H Zhang, <b>KL Hoffman</b>, IJ Easthausen, M Rajan et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8192694097316816663&btnI=1&hl=en">A predictive model of clinical deterioration among hospitalized COVID-19 patients by harnessing hospital course trajectories</a>, Journal of biomedical informatics, 118, 103794</td></tr>
<tr><td width="100%">M Plataki, D Pan, P Goyal, <b>K Hoffman</b>, JMK Choi, H Huang, MM Safford et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11386044110149325762&btnI=1&hl=en">Association of body mass index with morbidity in patients hospitalised with COVID-19</a>, BMJ open respiratory research, 8 (1), e000970</td></tr>
<tr><td width="100%">C Su, <b>KL Hoffman</b>, Z Xu, E Sanchez, II Siempos, JS Harrington et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=271018661855163907&btnI=1&hl=en">Evaluation of Albumin Kinetics in Critically Ill Patients With Coronavirus Disease 2019 Compared to Those With Sepsis-Induced Acute Respiratory Distress Syndrome</a>, Critical care explorations, 3 (12)</td></tr>
<tr><td width="100%">DR Price, E Benedetti, <b>KL Hoffman</b>, L Gomez-Escobar, S Alvarez-Mulett et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=13357077140000674818&btnI=1&hl=en">The maladaptive vascular response in COVID-19 acute respiratory distress syndrome and recovery</a>, medRxiv, </td></tr>
<tr><td width="100%">C Su, <b>K Hoffman</b>, X Zhenxing, E Sanchez, I Siempos, JS Harrington et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9579408226305777967&btnI=1&hl=en">Evaluation of albumin kinetics in mechanically ventilated patients with COVID-19 compared to those with sepsis-induced ARDS</a>, medRxiv, </td></tr>
<tr><td width="100%">DR Price, <b>KL Hoffman</b>, E Sanchez, AMK Choi, II Siempos (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=1803557617452849921&btnI=1&hl=en">Temporal trends of outcomes of neutropenic patients with ARDS enrolled in therapeutic clinical trials</a>, Intensive care medicine, 47 (1), 122-123</td></tr>
<tr><td width="100%">I Dıaz, N Williams, <b>KL Hoffman</b>, EJ Schenck (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Supplementary Materials for Non-parametric causal effects based on longitudinal modified treatment policies.</a>, , </td></tr>
<tr><td width="100%">JK Krishnan, MR Rajan, B Baer, C Ezeomah, SS Hill, MN Alshak et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Assessing Mortality Difference Across COVID-19 Intubation Strategies</a>, TP, P50. TP050 COVID: NONPULMONARY CRITICAL CARE, MECHANICAL VENTILATION …</td></tr>
<tr><td width="100%">GM Mondellini, J Qi, L Braghieri, A Pinsino, AJ Kim, T Melie, VR Feldman et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Effects of ACE Inhibitors, Angiotensin Receptor Blockers and Angiotensin Receptor-Neprilysin Inhibitors on Survival Free from Gastrointestinal Bleeding in HeartMate 3 Patients …</a>, The Journal of Heart and Lung Transplantation, 40 (4), S445</td></tr>
<tr><td width="100%"><b>K Hoffman</b> (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Covid‐19: a view from the sidelines</a>, Significance, 18 (1), 40-43</td></tr>
<tr><td width="100%">E Coskun, R Kalil, A Yin, G Wehmeyer, <b>K Hoffman</b>, R Kopparam, P Goyal et al. (2021) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Outcomes of the Oldest Old Admitted with COVID-19</a>, Journal of the American Geriatrics Society, S, S266-S266</td></tr>
</tbody></table>
<h3>2020</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">P Goyal, JJ Choi, LC Pinheiro, EJ Schenck, R Chen, A Jabri, MJ Satlin et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15546789143237910212&btnI=1&hl=en">Clinical characteristics of Covid-19 in New York city</a>, New England Journal of Medicine, 382 (24), 2372-2374</td></tr>
<tr><td width="100%">EJ Schenck, <b>K Hoffman</b>, P Goyal, J Choi, L Torres, K Rajwani, CW Tam et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=1669403615740349076&btnI=1&hl=en">Respiratory mechanics and gas exchange in COVID-19–associated respiratory failure</a>, Annals of the American Thoracic Society, 17 (9), 1158-1161</td></tr>
<tr><td width="100%">P Goyal, JB Ringel, M Rajan, JJ Choi, LC Pinheiro, HA Li, GT Wehmeyer et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8412293383774088657&btnI=1&hl=en">Obesity and COVID-19 in New York City: a retrospective cohort study</a>, Annals of internal medicine, 173 (10), 855-858</td></tr>
<tr><td width="100%">A Rahman, E Schelbaum, <b>K Hoffman</b>, I Diaz, H Hristov, R Andrews, S Jett et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=10026859675384066852&btnI=1&hl=en">Sex-driven modifiers of Alzheimer risk: a multimodality brain imaging study</a>, Neurology, 95 (2), e166-e178</td></tr>
<tr><td width="100%">WZ Zhang, MC Rice, <b>KL Hoffman</b>, C Oromendia, IZ Barjaktarevic et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15816584712892867645&btnI=1&hl=en">Association of urine mitochondrial DNA with clinical measures of COPD in the SPIROMICS cohort</a>, JCI insight, 5 (3)</td></tr>
<tr><td width="100%">T Chukir, Y Liu, <b>K Hoffman</b>, JP Bilezikian, A Farooki (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=13668613139527305116&btnI=1&hl=en">Calcitriol elevation is associated with a higher risk of refractory hypercalcemia of malignancy in solid tumors</a>, The Journal of Clinical Endocrinology & Metabolism, 105 (4), e1115-e1123</td></tr>
<tr><td width="100%">A Pinsino, GM Mondellini, EA Royzman, <b>KL Hoffman</b>, D D’Angelo et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=11958313871614318835&btnI=1&hl=en">Cystatin C-versus creatinine-based assessment of renal function and prediction of early outcomes among patients with a left ventricular assist device</a>, Circulation: Heart Failure, 13 (1), e006326</td></tr>
<tr><td width="100%">K Andreadis, <b>K Hoffman</b>, D D'Angelo, L Sulica (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=8272297891983826053&btnI=1&hl=en">Sulcus vocalis: Results of excision without reconstruction</a>, The Laryngoscope, 130 (9), 2208-2212</td></tr>
<tr><td width="100%">X Wu, S Poli De Frias, S Taheri, <b>K Hoffman</b>, I Easthausen, AJ Esposito et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15527651581241728321&btnI=1&hl=en">Differential Protein Expression in Rheumatoid Arthritis Interstitial Lung Disease</a>, D, D105. ILD EPIDEMIOLOGY II, A7796-A7796</td></tr>
<tr><td width="100%">Y Abdelghany, S ALMAraghi, R Simon, M Rice, <b>K Hoffman</b>, SA Kikkers et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">ASSOCIATION OF URINE AND BRONCHOALVEOLAR LAVAG LIPOCALIN-1 (NGAL) LEVELS WITH CLINICAL MEASURES OF COPD: AN ANALYSIS FROM THE SUBPOPULATIONS AND INTERMEDIATE OUTCOME MEASURES …</a>, Chest, 158 (4), A1662-A1663</td></tr>
<tr><td width="100%">K Ackerman, <b>K Hoffman</b>, I Diaz, K Ballman, R Kodiyanplakkal, AMK Choi et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Effect of Sepsis on Death as Modified by Solid Organ Transplantation</a>, A, A41. CRITICAL CARE: PREDICTING AND MEASURING OUTCOMES, A1631-A1631</td></tr>
<tr><td width="100%">LK Torres, <b>K Hoffman</b>, C Oromendia, I Diaz, E Schenck et al. (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Attributable Mortality of Acute Respiratory Distress Syndrome in Critically Ill Septic Patients: Estimation Using a Novel Causal Inference Method</a>, A, A41. CRITICAL CARE: PREDICTING AND MEASURING OUTCOMES, A1645-A1645</td></tr>
<tr><td width="100%">HS Bhatia, J Bailey, O Unlu, <b>K Hoffman</b>, RJ Kim (2020) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Response to “Direct oral anticoagulants in patients with atrial fibrillation and chronic kidney disease”</a>, Pacing and Clinical Electrophysiology, 43 (2), 267-267</td></tr>
</tbody></table>
<h3>2019</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%">CP Soneru, CA Riley, <b>K Hoffman</b>, A Tabaee, TH Schwartz (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=14358092136367648923&btnI=1&hl=en">Intra-operative MRI vs endoscopy in achieving gross total resection of pituitary adenomas: a systematic review</a>, Acta Neurochirurgica, 161 (8), 1683-1698</td></tr>
<tr><td width="100%">U Khan, C Peña, J Brouwer, <b>K Hoffman</b>, AR Choudhury, C Zhang et al. (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=9452324282192527182&btnI=1&hl=en">Impact of antibiotic use on response to treatment with immune checkpoint inhibitors.</a>, Journal of Clinical Oncology, 37 (4_suppl), 143-143</td></tr>
<tr><td width="100%">HS Bhatia, J Bailey, O Unlu, <b>K Hoffman</b>, RJ Kim (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=15268412750231466588&btnI=1&hl=en">Efficacy and safety of direct oral anticoagulants in patients with atrial fibrillation and chronic kidney disease</a>, Pacing and Clinical Electrophysiology, 42 (11), 1463-1470</td></tr>
<tr><td width="100%">A Pinsino, A Gaudig, <b>KL Hoffman</b>, D D'Angelo, EA Royzman et al. (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=6746591601005744742&btnI=1&hl=en">Digoxin is Associated with Decreased Survival Free from Hemocompatibility-Related Adverse Events in LVAD Patients-A Propensity Score Matched Analysis</a>, The Journal of Heart and Lung Transplantation, 38 (4), S170</td></tr>
<tr><td width="100%">L Comisar, E Schenck, <b>K Hoffman</b>, C Oromendia, I Siempos, E Sanchez et al. (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">IMPACT OF BMI ON OUTCOME OF PATIENTS WITH HEMATOLOGIC MALIGNANCIES IN THE ICU</a>, Chest, 156 (4), A1143-A1144</td></tr>
<tr><td width="100%">AM Zuver, <b>KL Hoffman</b>, D D'Angelo, D Onat, EA Royzman, JC Hupf et al. (2019) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">Microbiome-Derived TMAO Exhibits No Protective Effect against GIB in LVAD Patients</a>, The Journal of Heart and Lung Transplantation, 38 (4), S195-S196</td></tr>
</tbody></table>
<h3>2015</h3>
<table class="publication-table" border="10px solid blue" cellspacing="0" cellpadding="6" rules="", frame=""><tbody>
<tr><td width="100%"><b>K Hoffman</b> (2015) <a href="https://scholar.google.com/scholar?oi=bibs&cluster=NA&btnI=1&hl=en">A Beautiful Affliction: Tracing the Role of Mentally Ill Artists in Reducing the Negative Stigma of Mental Illness</a>, University of Detroit Mercy, </td></tr>
</tbody></table>
